# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
#  vmImage: 'Ubuntu 16.04'
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '10'
  Patch: '0'


steps:
- script: |
    dotnet restore bleak.Sql.Minifier/bleak.Sql.Minifier.csproj
    dotnet restore bleak.Sql.Minifier.Tests/bleak.Sql.Minifier.Tests.csproj
	dotnet restore bleak.Sql.VersionManager/bleak.Sql.VersionManager.csproj
    dotnet restore bleak.Sql.VersionManager.Redshift\bleak.Sql.VersionManager.Redshift.csproj
	dotnet restore bleak.Sql.VersionManager.Redshift.Tests\bleak.Sql.VersionManager.Redshift.Tests.csproj
    dotnet restore bleak.Sql.VersionManager.SqlServer\bleak.Sql.VersionManager.SqlServer.csproj
	dotnet restore bleak.Sql.VersionManager.SqlServer.Tests\bleak.Sql.VersionManager.SqlServer.Tests.csproj
  displayName: Restore
  name: Restore

- script: |
    dotnet build bleak.Sql.Minifier/bleak.Sql.Minifier.csproj --configuration $(buildConfiguration)
    dotnet build bleak.Sql.Minifier.Tests/bleak.Sql.Minifier.Tests.csproj --configuration $(buildConfiguration)
	dotnet build bleak.Sql.VersionManager/bleak.Sql.VersionManager.csproj
    dotnet build bleak.Sql.VersionManager.Redshift\bleak.Sql.VersionManager.Redshift.csproj
	dotnet build bleak.Sql.VersionManager.SqlServer\bleak.Sql.VersionManager.SqlServer.csproj
  displayName: Build
  name: Build

  
- script: |
    dotnet test bleak.Sql.Minifier.Tests --configuration $(buildConfiguration) --logger trx
  displayName: Tests
  name: Tests
# Not currently running the tests for SqlServer and Redshift VersionManagers... since these tests require connection to a database.
# Shame on Jamal for making an integration test and not a unit test.

- script: |
    dotnet pack bleak.Sql.Minifier/bleak.Sql.Minifier.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
	dotnet pack bleak.Sql.VersionManager/bleak.Sql.VersionManager.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
    dotnet pack bleak.Sql.VersionManager.Redshift\bleak.Sql.VersionManager.Redshift.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
	dotnet pack bleak.Sql.VersionManager.SqlServer\bleak.Sql.VersionManager.SqlServer.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
  displayName: Pack
  name: Pack

- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts

- task: NuGetCommand@2
  displayName: Deploy to Nuget.org
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGetConnection'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
